spring.application.name=item-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:item-service}
spring.datasource.driverClassName=${DATABASE_DRIVER:org.h2.Driver}
spring.datasource.username=${DATABASE_USERNAME:admin}
spring.datasource.password=${DATABASE_PASSWORD:password}

spring.jpa.database-platform=${JPA_DIALECT:org.hibernate.dialect.H2Dialect}
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true

microservices.category.url=${MICROSERVICES_CATEGORY_URL: http://localhost:8082}
